config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'feedbacks/new'
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end
  resources :badges, only: :index
  resources :feedbacks, only: %i[new create]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end

  end

  namespace :admin do
    resources :gists, only: :index
    resources :badges do
      patch :update_inline, on: :member
    end
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/helpers/gists_helper.rb
# frozen_string_literal: true

module GistsHelper
  def gist_hash(url)
    url.split('/').last
  end
end

app/views/admin/gists/_gist.html.slim
tr
  td = link_to gist.question.body.truncate(25), admin_question_path(gist.question.id)
  td = link_to gist_hash(gist.url), gist.url, target: '_blank'
  td = gist.user.email

app/views/admin/gists/index.html.slim
.row.justify-content-center.mt-3
  .col.col-md-6
    h1= t('.header')
    table.table.table-sm
      thead
        tr
          th scope="col" = t('.question')
          th scope="col" = t('.gist_url')
          th scope="col" = t('.user')
      = render @gists
    = link_to t('navigation.back'), admin_tests_path, class: 'nav-link'