config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'feedbacks/new'
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end
  resources :badges, only: :index
  resources :feedbacks, only: %i[new create]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end

  end

  namespace :admin do
    resources :gists, only: :index
    resources :badges do
      patch :update_inline, on: :member
    end
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { maximum: 50 }
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  PASSING_SCORE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  scope :success, -> { where('score >= ?', PASSING_SCORE) }

  before_validation :before_validation_set_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = next_question
    save!
  end

  def result
    (100.00 / test.questions.size) * correct_questions
  end

  def save_result
    update!(score: result)
  end

  def passed?
    result >= PASSING_SCORE
  end

  def question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  private

  def before_validation_set_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  include EventsHelper

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call
    if result.success?
      Gist.create!(user: @test_passage.user, question: @test_passage.current_question, url: result.gist_url)
      flash[:notice] = view_context.link_to(t('.services.gist.success'), result.gist_url, target: :blank)
    else
      flash[:alert] = t('.services.gist.failure')
    end

    redirect_to @test_passage
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      check_reward(@test_passage)
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/views/test_passages/result.html.slim
h1 = t('.header', title: @test_passage.test.title)
p Your result below:
- if @test_passage.passed?
    div Well done! Correct answers:
    .green #{@test_passage.result} %
- else
    div You failed! Correct answers:
    .red #{@test_passage.result} %
= link_to 'Tests', tests_path(@test_passage.test)

app/views/test_passages/show.html.slim
.progress
  .progress_bar role="progressbar" style=("width: 0%;") aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"

- if @test_passage.test.timer?
    = t('.timer')
    = content_tag :span, '', class: 'timer', data: { timer: @test_passage.remaining_time }

h1
  ' Passing the
  = @test_passage.test.title

p
  'Question number:
  = @test_passage.question_number
p
  'Total questions:
  = @test_passage.test.questions.size
p
  b = @test_passage.current_question.body


= form_with url: test_passage_path(@test_passage),
            local: true,
            method: :put,
            id: :passage,
            data: { current_question: @test_passage.question_number,
            questions_size: @test_passage.test.questions.size} do |f|
  = f.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b|
    .field
    = b.check_box id: "answer_ids_#{b.object.id}"
    = b.label
  .action
  = link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post
  = f.submit 'Next'

= link_to 'Stop test', tests_path