config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'feedbacks/new'
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end
  resources :badges, only: :index
  resources :feedbacks, only: %i[new create]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end

  end

  namespace :admin do
    resources :gists, only: :index
    resources :badges do
      patch :update_inline, on: :member
    end
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { maximum: 50 }
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  before_action :set_test, only: %i[index new create]
  before_action :set_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def edit; end

  def show; end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test_id)
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    header = question.new_record? ? 'Create new' : 'Edit'
    "#{header} #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.slim
= question_header(@question)
= form_with model: [:admin, @test, @question] do |f|
  = render 'shared/errors', resource: @question
  .field
    = f.label :body
    = f.text_field :body, id: :question_body
  .actions
    = f.submit 'Save'

= link_to 'Back', admin_test_path(@question.test)

app/views/admin/questions/_question.html.slim
tr
  td = question.body
  td = link_to 'Show', admin_question_path(question)
  td = link_to 'Edit', edit_admin_question_path(question)
  td = link_to 'Delete',
               admin_question_path(question),
               method: :delete,
               data: { confirm: 'Are you sure?' }

app/views/admin/questions/edit.html.slim
- provide(:title, 'Edit question')
= render 'form'

= link_to 'Back', admin_tests_path(@question.test)

app/views/admin/questions/new.html.slim
- provide(:title, 'New question')
= render 'form'

= link_to 'Back', admin_test_path(@test)

app/views/admin/questions/show.html.slim
- provide(:title, 'Show question')
h1
  'Questions id:
  = @question.id
br/
p
  'Body:
  = @question.body
br/
= link_to 'New answer', new_admin_question_answer_path(@question)

table
  tr
    th Answers
    th colspan='3' Actions
    = render partial: 'admin/answers/answer', collection: @question.answers


= link_to 'Back', admin_test_path(@question.test)
br/
= link_to 'Edit', edit_admin_question_path(@question)
br/