config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'feedbacks/new'
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end
  resources :badges, only: :index
  resources :feedbacks, only: %i[new create]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end

  end

  namespace :admin do
    resources :gists, only: :index
    resources :badges do
      patch :update_inline, on: :member
    end
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question, counter_cache: true
  scope :correct, -> { where(correct: true) }

  validates :body, presence: true, length: { maximum: 50 }
  validate :validate_max_answers, on: :create

  private

  def validate_max_answers
    errors.add(:question, 'max 4 answers') if question.answers.size >= 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  BADGE_TYPE = %w[first_try_complete? whole_category_complete? all_by_level?].freeze

  has_many :users, through: :user_badges
  has_many :user_badges, dependent: :destroy

  validates :name, :award_rule, presence: true
  validates :image, presence: true, format: URI::regexp(%w(http https))
  validates :name, uniqueness: true
  validates :award_rule, uniqueness: { scope: :badge_param }

end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(title: :asc) }
  has_many :tests, dependent: :nullify

  validates :title, presence: true,
                    uniqueness: true

end

app/models/feedback.rb
# frozen_string_literal: true

class Feedback
  include ActiveModel::Model

  attr_accessor :body

  validates :body, presence: true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { maximum: 50 }
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category, lambda { |name|
                        joins(:category)
                          .where(categories: { title: name })
                          .order(title: :desc)
                      }

  validates :timer, numericality: { only_integer: true, greater_than_or_equal_to: 0 },
                                                                    allow_blank: true
  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.titles_by_category(name)
    by_category(name).pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  PASSING_SCORE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  scope :success, -> { where('score >= ?', PASSING_SCORE) }

  before_validation :before_validation_set_question, on: :create

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = next_question
    save!
  end

  def result
    (100.00 / test.questions.size) * correct_questions
  end

  def save_result
    update!(score: result)
  end

  def passed?
    result >= PASSING_SCORE
  end

  def question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  private

  def before_validation_set_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def tests_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
# frozen_string_literal: true

class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_badges = current_user.badges
    @badges = Badge.all
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: %i[start]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'TestGuru'
    if page_title.empty?
      base_title
    else
      page_title + '|' + base_title
    end
  end

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    "http://github.com/#{author}/#{repo}"
  end

  private

  def welcome_message
    "Welcome #{ current_user.email } Guru" if user_signed_in?
  end
end

app/helpers/badges_helper.rb
module BadgesHelper

  def not_earned_badges
    @badges - @user_badges
  end

  def award_rule_name
    Badge::BADGE_TYPE.map { |rule| [t(rule, scope: 'admin.badges.form.award_rule_name'), rule] }
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
# frozen_string_literal: true

module GistsHelper
  def gist_hash(url)
    url.split('/').last
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    header = question.new_record? ? 'Create new' : 'Edit'
    "#{header} #{question.test.title} Question"
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  def test_header(test)
    header = test.new_record? ? 'Create new' : 'Edit'
    "#{header} #{test.title} Test"
  end

end

app/views/layouts/_footer.html.slim
footer
  p
    'Текущий год
    = current_year
  p Автор umeca90
  = link_to 'GitHub', github_url('umeca90', 'test-guru'), target: '_blank'
  p TestGuru is a tutorial ROR app
  = link_to 'Учебный проект в онлайн-школе Thinknetica','http://thinknetica.com', target: '_blank'
  p
    = link_to(t('navigation.feedback'), new_feedback_path)

app/views/layouts/_header.html.slim
.header.guru-header.guru-header-dark
  .top-bar
    .top-bar-brand
      = link_to 'Test-Guru', root_path
      img#logo alt=""  src="https://image.flaticon.com/icons/png/512/29/29302.png"
      - if user_signed_in?
        li.nav-user = welcome_message
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Account
            b.caret
          ul.dropdown-menu
            li= link_to "Logout", destroy_user_session_path, method: :delete
            li.divider
      - else
        li= link_to "Log in", new_user_session_path
        li= link_to "Register", new_user_registration_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    title
      = full_title(yield(:title))

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/admin/nav'
    main
      .container
        = render 'shared/flash', flash: flash
        = yield
      = render 'layouts/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    title
      = full_title(yield(:title))

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    = render 'shared/nav'
    main.main.bg-light
      .container
        = render 'shared/flash', flash: flash
        = yield
      = render 'layouts/footer'

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do
    h2
      = t('.header', count: resource.errors.count)
    - resource.errors.full_messages.each do |message|
      ul
        li = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :div, message.html_safe, class: "alert alert-#{key}", role: "alert"

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  #navbarResponsive.collapse.navbar-collapse
    ul.nav.navbar-nav.navbar-right.ml-auto
      - if user_signed_in?
        li.nav-user = welcome_message
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Account
            b.caret
          ul.dropdown-menu
            li= link_to "Logout", destroy_user_session_path, method: :delete
            li.divider
      - else
        li= link_to "Log in", new_user_session_path
        li= link_to "Register", new_user_registration_path

app/views/shared/admin/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .navbar-brand = link_to 'Test-Guru|Admin Panel', admin_tests_path
  img#logo alt=""  src="https://image.flaticon.com/icons/png/512/1332/1332121.png"
  #navbarResponsive.collapse.navbar-collapse
    ul.nav.navbar-nav.navbar-right.ml-auto
      - if user_signed_in?
        li.nav-user = welcome_message
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Account
            b.caret
          ul.dropdown-menu
            li= link_to "Logout", destroy_user_session_path, method: :delete
            li.divider
      - else
        li= link_to "Log in", new_user_session_path
        li= link_to "Register", new_user_registration_path